### PR TITLE
upgrade grpcio

### PR DESCRIPTION
**Pull request by odelame**

### CODE REVIEW

**Comment by Jongy** [comment]
image

:sweat_smile: many upgrade-grcpio PRs.

**Comment by odelame** [comment]
@d3dave 
https://github.com/Granulate/granulate/pull/16705 - Build passes.

**Comment by Jongy** [comment]
There are several issues with grpcio as written in other PRs. we're not handling it now @michelhe

**Comment by Jongy** [comment]
Closing in favor of https://github.com/Granulate/granulate-utils/pull/139

**Pull request closed without merging**
